describe('Practicando Cypress con la pagina de Tricentis Demo Web Shop', () => {
    beforeEach(() => {
        //Esto es para no repetir el comando para visitar la pagina en cada test
        cy.visit('https://demowebshop.tricentis.com/')
    })

    it('Validacion del titulo de la pagina', () => {
        cy.title().should('include', 'Demo Web Shop')
    })

    //Se colocan los pasos en forma de logs
    it('Validacion de campos en un formulario de registro Demo Web Shop', () => {
        cy.log("Paso 1 En la pantalla principal dar clic en Register")
        cy.get('.ico-register').should('be.visible').and('have.text', 'Register').click()
        cy.log("Paso 2 Validacion del titulo del formulario Register, debe ser visible y coincidir con el texto")
        cy.get('h1').should('be.visible').and('have.text', 'Register')
        cy.log("Paso 3 Validacion de etiqueta Your Personal Details, debe ser visible y coincidir con el texto")
        cy.get('.page-body > :nth-child(2) > .title > strong').should('be.visible').and('have.text', 'Your Personal Details')
        cy.log("Paso 4 Validacion de etiqueta Gender, debe ser visible y coincidir con el texto")
        cy.get(':nth-child(2) > .form-fields > :nth-child(1) > :nth-child(1)').should('be.visible').and('have.text', 'Gender:')
        cy.log("Paso 5 Validacion de radio button Male, debe estar visible, habilitado y sin seleccionar")
        cy.get('#gender-male').should('be.visible').and('not.be.disabled').and('not.be.checked')
        cy.log("Paso 6 Validacion de etiqueta Male, debe ser visible y coincidir con el texto")
        cy.get(':nth-child(2) > .forcheckbox').should('be.visible').and('have.text', 'Male')
        cy.log("Paso 7 Validacion de radio button Female, debe estar visible, habilitado y sin seleccionar")
        cy.get('#gender-female').should('be.visible').and('not.be.disabled').and('not.be.checked')
        cy.log("Paso 8 Validacion de etiqueta Female, debe ser visible y coincidir con el texto")
        cy.get(':nth-child(3) > .forcheckbox').should('be.visible').and('have.text', 'Female')
        cy.log("Paso 9 Validacion de etiqueta First name:, debe ser visible y coincidir con el texto")
        cy.get(':nth-child(2) > .form-fields > :nth-child(2) > label').should('be.visible').and('have.text', 'First name:')
        cy.log("Paso 10 Validacion de Textbox First name, debe ser visible, estar habilitada y sin texto")
        cy.get('#FirstName').should('be.visible').and('not.be.disabled').and('have.text', '')
        cy.log("Paso 11 Validacion de campo First name campo obligatorio, debe ser visible")
        cy.get(':nth-child(2) > .form-fields > :nth-child(2) > .required').should('be.visible')
        cy.log("Paso 12 Validacion de etiqueta Last name:, debe ser visible y coincidir con el texto")
        cy.get('.form-fields > :nth-child(3) > label').should('be.visible').and('have.text', 'Last name:')
        cy.log("Paso 13 Validacion de Textbox Last name, debe ser visible, estar habilitada y sin texto")
        cy.get('#LastName').should('be.visible').and('not.be.disabled').and('have.text', '')
        cy.log("Paso 14 Validacion de campo Last name campo obligatorio, debe ser visible")
        cy.get(':nth-child(3) > .required').should('be.visible')
        cy.log("Paso 15 Validacion de etiqueta Email:, debe ser visible y coincidir con el texto")
        cy.get(':nth-child(4) > label').should('be.visible').and('have.text', 'Email:')
        cy.log("Paso 16 Validacion de Textbox Email, debe ser visible, estar habilitada y sin texto")
        cy.get('#Email').should('be.visible').and('not.be.disabled').and('have.text', '')
        cy.log("Paso 17 Validacion de campo Email campo obligatorio, debe ser visible")
        cy.get(':nth-child(4) > .required').should('be.visible')
        cy.log("Paso 18 Validacion de etiqueta Your Password, debe ser visible y coincidir con el texto")
        cy.get('.page-body > :nth-child(3) > .title > strong').should('be.visible').and('have.text', 'Your Password')
        cy.log("Paso 19 Validacion de etiqueta Password:, debe ser visible y coincidir con el texto")
        cy.get(':nth-child(3) > .form-fields > :nth-child(1) > label').should('be.visible').and('have.text', 'Password:')
        cy.log("Paso 20 Validacion de Textbox Password, debe ser visible, estar habilitada y sin texto")
        cy.get('#Password').should('be.visible').and('not.be.disabled').and('have.text', '')
        cy.log("Paso 21 Validacion de campo Password campo obligatorio, debe ser visible")
        cy.get(':nth-child(1) > .required').should('be.visible')
        cy.log("Paso 22 Validacion de etiqueta Confirm password:, debe ser visible y coincidir con el texto")
        cy.get(':nth-child(3) > .form-fields > :nth-child(2) > label').should('be.visible').and('have.text', 'Confirm password:')
        cy.log("Paso 23 Validacion de Textbox Confirm Password, debe ser visible, estar habilitada y sin texto")
        cy.get('#ConfirmPassword').should('be.visible').and('not.be.disabled').and('have.text', '')
        cy.log("Paso 24 Validacion de campo Confirm password campo obligatorio, debe ser visible")
        cy.get(':nth-child(3) > .form-fields > :nth-child(2) > .required').should('be.visible')
        cy.log("Paso 25 Validacion de boton Register, debe ser visible, estar habilitado")
        cy.get('#register-button').should('be.visible').and('not.be.disabled')
    })

    it('Validacion de avisos de campo obligatorios e inputs incorrectos', () => {
        cy.log("Paso 1 En la pantalla principal dar clic en Register")
        cy.get('.ico-register').should('be.visible').and('have.text', 'Register').click()
        cy.log("Paso 2 Hacer clic en el boton de register sin llenar ningun campo")
        cy.get('#register-button').click()
        cy.log("Paso 3 Validacion de aviso de First name is required. debe ser visible y coincidir con el texto")
        cy.get(':nth-child(2) > .form-fields > :nth-child(2) > .field-validation-error > span').should('be.visible').and('have.text', 'First name is required.')
        cy.log("Paso 4 Validacion de aviso de Last name is required. debe ser visible y coincidir con el texto")
        cy.get(':nth-child(3) > .field-validation-error > span').should('be.visible').and('have.text', 'Last name is required.')
        cy.log("Paso 5 Validacion de aviso de Email is required. debe ser visible y coincidir con el texto")
        cy.get(':nth-child(4) > .field-validation-error > span').should('be.visible').and('have.text', 'Email is required.')
        cy.log("Paso 6 Validacion de aviso de Password is required. debe ser visible y coincidir con el texto")
        cy.get(':nth-child(1) > .field-validation-error > span').should('be.visible').and('have.text', 'Password is required.')
        cy.log("Paso 7 Validacion de aviso de confirm password obligatorio(Password is required.), debe ser visible y coincidir con el texto")
        cy.get(':nth-child(3) > .form-fields > :nth-child(2) > .field-validation-error > span').should('be.visible').and('have.text', 'Password is required.')
        cy.log("Paso 8 Validacion de aviso de Wrong email, debe ser visible y coincidir con el texto")
        cy.get('#Email').type('123')    
        cy.get(':nth-child(4) > .field-validation-error > span').should('be.visible').and('have.text', 'Wrong email')
        cy.log("Paso 9 Validacion de aviso de The password should have at least 6 characters. debe ser visible y coincidir con el texto")
        cy.get('#Password').type('12345')
        cy.get(':nth-child(1) > .field-validation-error > span').should('be.visible').and('have.text', 'The password should have at least 6 characters.')
        cy.log("Paso 10 Validacion de aviso de The password and confirmation password do not match. debe ser visible y coincidir con el texto")
        cy.get('#Password').clear().type('Test01')
        cy.get('#ConfirmPassword').type('Test02')
        cy.get(':nth-child(3) > .form-fields > :nth-child(2) > .field-validation-error > span').should('be.visible').and('have.text', 'The password and confirmation password do not match.')
    })

    it('Validacion de alta de cliente nuevo sin genero', () => {
        cy.log("Paso 1 En la pantalla principal dar clic en Register")
        cy.get('.ico-register').click()
        cy.log("Paso 2 Ingresar un texto valido en el campo First name")
        cy.get('#FirstName').type('Test Name')  
        cy.log("Paso 3 Ingresar un texto valido en el campo Last name")
        cy.get('#LastName').type('Test Last Name')
        cy.log("Paso 4 Ingresar un correo valido en el campo Email")
        cy.get('#Email').type(`${Date.now()}@sample.com`)
        cy.log("Paso 5 Ingresar una contraseña valida en el campo Password")
        cy.get('#Password').type('Testing10')
        cy.log("Paso 6 Ingresar la misma contraseña valida en el campo Confirm password")
        cy.get('#ConfirmPassword').type('Testing10')
        cy.log("Paso 7 Se da clic en el boton de Register")
        cy.get('#register-button').click()
        cy.log("Paso 8 Se valida el mensaje de registro de usuario exitoso, aceptar y cerrar sesion")
        cy.get('.result').should('be.visible')
        cy.get('.page-body > .buttons > .button-1').click()
        cy.get('.ico-logout').click()
        cy.get('.ico-register').should('be.visible').and('have.text', 'Register')
    })

    it('Validacion de alta de cliente nuevo masculino', () => {
        cy.log("Paso 1 En la pantalla principal dar clic en Register")
        cy.get('.ico-register').click()
        cy.log("Paso 2 Se selecciona el radio button de Male")
        cy.get('#gender-male').check()
        cy.log("Paso 3 Ingresar un texto valido en el campo First name")
        cy.get('#FirstName').type('Test Name')  
        cy.log("Paso 4 Ingresar un texto valido en el campo Last name")
        cy.get('#LastName').type('Test Last Name')
        cy.log("Paso 5 Ingresar un correo valido en el campo Email")
        cy.get('#Email').type(`${Date.now()}@sample.com`)
        cy.log("Paso 6 Ingresar una contraseña valida en el campo Password")
        cy.get('#Password').type('Testing10')
        cy.log("Paso 7 Ingresar la misma contraseña valida en el campo Confirm password")
        cy.get('#ConfirmPassword').type('Testing10')
        cy.log("Paso 8 Se da clic en el boton de Register")
        cy.get('#register-button').click()
        cy.log("Paso 9 Se valida el mensaje de registro de usuario exitoso, aceptar y cerrar sesion")
        cy.get('.result').should('be.visible')
        cy.get('.page-body > .buttons > .button-1').click()
        cy.get('.ico-logout').click()
        cy.get('.ico-register').should('be.visible').and('have.text', 'Register')
    })

    it('Validacion de alta de cliente nuevo femenino', () => {
        cy.log("Paso 1 En la pantalla principal dar clic en Register")
        cy.get('.ico-register').click()
        cy.log("Paso 2 Se selecciona el radio button de Male")
        cy.get('#gender-female').check()
        cy.log("Paso 3 Ingresar un texto valido en el campo First name")
        cy.get('#FirstName').type('Test Name')  
        cy.log("Paso 4 Ingresar un texto valido en el campo Last name")
        cy.get('#LastName').type('Test Last Name')
        cy.log("Paso 5 Ingresar un correo valido en el campo Email")
        cy.get('#Email').type(`${Date.now()}@sample.com`)
        cy.log("Paso 6 Ingresar una contraseña valida en el campo Password")
        cy.get('#Password').type('Testing10')
        cy.log("Paso 7 Ingresar la misma contraseña valida en el campo Confirm password")
        cy.get('#ConfirmPassword').type('Testing10')
        cy.log("Paso 8 Se da clic en el boton de Register")
        cy.get('#register-button').click()
        cy.log("Paso 9 Se valida el mensaje de registro de usuario exitoso, aceptar y cerrar sesion")
        cy.get('.result').should('be.visible')
        cy.get('.page-body > .buttons > .button-1').click()
        cy.get('.ico-logout').click()
        cy.get('.ico-register').should('be.visible').and('have.text', 'Register')
    })

    it('Validacion de alta de cliente repetido', () => {
        cy.log("Paso 1 En la pantalla principal dar clic en Register")
        cy.get('.ico-register').click()
        cy.log("Paso 2 Se selecciona el radio button de Male")
        cy.get('#gender-female').check()
        cy.log("Paso 3 Ingresar un texto valido en el campo First name")
        cy.get('#FirstName').type('Test Name')  
        cy.log("Paso 4 Ingresar un texto valido en el campo Last name")
        cy.get('#LastName').type('Test Last Name')
        cy.log("Paso 5 Ingresar un correo valido en el campo Email")
        cy.get('#Email').type('Sample@sample.com')
        cy.log("Paso 6 Ingresar una contraseña valida en el campo Password")
        cy.get('#Password').type('Testing10')
        cy.log("Paso 7 Ingresar la misma contraseña valida en el campo Confirm password")
        cy.get('#ConfirmPassword').type('Testing10')
        cy.log("Paso 8 Se da clic en el boton de Register")
        cy.get('#register-button').click()
        cy.log("Paso 9 Se valida el mensaje de usuario repetido (The specified email already exists), debe ser visible y coincidir con el texto")
        cy.get('.validation-summary-errors > ul > li').should('be.visible').and('have.text', 'The specified email already exists')

    })

    it('Validacion de opciones de barra de navegacion', () => {
        cy.log("Paso 1 Ingresar a la opcion Books de la barra de navegacion")
        cy.get('.top-menu > :nth-child(1) > a').click()
        cy.log("Paso 2 Validar el titulo y ruta de la navegacion exitosa")
        cy.get('.current-item').should('be.visible').and('have.text', 'Books')
        cy.get('h1').should('be.visible').and('have.text', 'Books')
        cy.log("Paso 3 Ingresar a la opcion Computers de la barra de navegacion")
        cy.get('.top-menu > :nth-child(2) > [href="/computers"]').click()
        cy.log("Paso 4 Validar el titulo y ruta de la navegacion exitosa")
        cy.get('.current-item').should('be.visible').and('have.text', 'Computers')
        cy.get('h1').should('be.visible').and('have.text', 'Computers')
        cy.log("Paso 5 Ingresar a la opcion Electronics de la barra de navegacion")
        cy.get('.top-menu > :nth-child(3) > [href="/electronics"]').click()
        cy.log("Paso 6 Validar el titulo y ruta de la navegacion exitosa")
        cy.get('.current-item').should('be.visible').and('have.text', 'Electronics')
        cy.get('h1').should('be.visible').and('have.text', 'Electronics')
        cy.log("Paso 7 Ingresar a la opcion Apparel & Shoes de la barra de navegacion")
        cy.get('.top-menu > :nth-child(4) > a').click()
        cy.log("Paso 8 Validar el titulo y ruta de la navegacion exitosa")
        cy.get('.current-item').should('be.visible').and('have.text', 'Apparel & Shoes')
        cy.get('h1').should('be.visible').and('have.text', 'Apparel & Shoes')
        cy.log("Paso 9 Ingresar a la opcion Digital Downloads de la barra de navegacion")
        cy.get('.top-menu > :nth-child(5) > a').click()
        cy.log("Paso 10 Validar el titulo y ruta de la navegacion exitosa")
        cy.get('.current-item').should('be.visible').and('have.text', 'Digital downloads')
        cy.get('h1').should('be.visible').and('have.text', 'Digital downloads')
        cy.log("Paso 11 Ingresar a la opcion Jewerly de la barra de navegacion")
        cy.get('.top-menu > :nth-child(6) > a').click()
        cy.log("Paso 12 Validar el titulo y ruta de la navegacion exitosa")
        cy.get('.current-item').should('be.visible').and('have.text', 'Jewelry')
        cy.get('h1').should('be.visible').and('have.text', 'Jewelry')           
        cy.log("Paso 13 Ingresar a la opcion Gift cards de la barra de navegacion")
        cy.get('.top-menu > :nth-child(7) > a').click()
        cy.log("Paso 14 Validar el titulo y ruta de la navegacion exitosa")        
        cy.get('.current-item').should('be.visible').and('have.text', 'Gift Cards')
        cy.get('h1').should('be.visible').and('have.text', 'Gift Cards') 
        cy.log("Paso 15 Regresar a la Home Page dando clic en la imagen con el logo de la pagina")  
        cy.get('.header-logo > a > img').click()
    
    })         

    it('Validacion de opciones disponibles en dropdown Sort By', () => {
        cy.log("Paso 1 Ingresar a la opcion Books de la barra de navegacion")
        cy.get('.top-menu > :nth-child(1) > a').click()
        cy.log("Paso 2 Seleccionar del dropdown la opcion 1 y validar el nuevo orden de los objetos")
        cy.get('#products-orderby').select('Name: A to Z')
        cy.get(':nth-child(1) > .product-item > .details > .product-title > a').should('have.text', 'Computing and Internet')
        cy.log("Paso 3 Seleccionar del dropdown la opcion 2 y validar el nuevo orden de los objetos")
        cy.get('#products-orderby').select('Name: Z to A')
        cy.get(':nth-child(1) > .product-item > .details > .product-title > a').should('have.text', 'Science')
        cy.log("Paso 4 Seleccionar del dropdown la opcion 3 y validar el nuevo orden de los objetos")
        cy.get('#products-orderby').select('Price: Low to High')
        cy.get(':nth-child(1) > .product-item > .details > .add-info > .prices > .actual-price').should('have.text', '10.00')
        cy.log("Paso 5 Seleccionar del dropdown la opcion 4 y validar el nuevo orden de los objetos")
        cy.get('#products-orderby').select('Price: High to Low')
        cy.get(':nth-child(1) > .product-item > .details > .add-info > .prices > .actual-price').should('have.text', '51.00')
        cy.log("Paso 6 Seleccionar del dropdown la opcion 5 y validar el nuevo orden de los objetos")
        cy.get('#products-orderby').select('Created on')
        cy.get(':nth-child(1) > .product-item > .details > .product-title > a') .should('have.text', 'Copy of Computing and Internet EX')
        cy.log("Paso 7 Regresar a la Home Page dando clic en la imagen con el logo de la pagina")  
        cy.get('.header-logo > a > img').click()

    })

        it('Validacion de opciones disponibles escondidas en barra de navegacion', () => {
        cy.log("Paso 1 Ingresar a la opcion oculta Desktops de la barra de navegacion")
        cy.get('body > div.master-wrapper-page > div.master-wrapper-content > div.header-menu > ul.top-menu > li:nth-child(2) > ul > li:nth-child(1) > a').click({force:true})
        cy.get('h1').should('be.visible').and('have.text', 'Desktops')
        cy.log("Paso 2 Ingresar a la opcion oculta Notebooks de la barra de navegacion")
        cy.get('body > div.master-wrapper-page > div.master-wrapper-content > div.header-menu > ul.top-menu > li:nth-child(2) > ul > li:nth-child(2) > a').click({force:true})
        cy.get('h1').should('be.visible').and('have.text', 'Notebooks')
        cy.log("Paso 3 Ingresar a la opcion oculta Accessories de la barra de navegacion")
        cy.get('body > div.master-wrapper-page > div.master-wrapper-content > div.header-menu > ul.top-menu > li:nth-child(2) > ul > li:nth-child(3) > a').click({force:true})
        cy.get('h1').should('be.visible').and('have.text', 'Accessories')   
        cy.log("Paso 4 Ingresar a la opcion oculta Camera, photo de la barra de navegacion")
        cy.get('body > div.master-wrapper-page > div.master-wrapper-content > div.header-menu > ul.top-menu > li:nth-child(3) > ul > li:nth-child(1) > a').click({force:true})
        cy.get('h1').should('be.visible').and('have.text', 'Camera, photo') 
        cy.log("Paso 5 Ingresar a la opcion oculta Cell phones de la barra de navegacion")
        cy.get('body > div.master-wrapper-page > div.master-wrapper-content > div.header-menu > ul.top-menu > li:nth-child(3) > ul > li:nth-child(2) > a').click({force:true})
        cy.get('h1').should('be.visible').and('have.text', 'Cell phones')  

    })

})